### ISSUE TITLE
Falsetweaks Crash on startup

### ISSUE THREAD

**Issue by iamsoNewBee** [quentin452/Multithreadingandtweaks#12] opened 2023-05-07 00:22 UTC
### Description

<img width="396" alt="image" src="https://user-images.githubusercontent.com/98573273/236651611-07640226-713d-46f0-b3b4-3dc9611db757.png">
NO [UniMixins] ? IS IT RIGHT?

**Comment by quentin452** [comment] 2023-05-07 08:42
not a problem with Gasstation , its a problem with falsetweaks

**Comment by iamsoNewBee** [comment] 2023-05-07 08:44
but i can run it without any crash

**Comment by iamsoNewBee** [comment] 2023-05-07 08:44
??????

**Comment by quentin452** [comment] 2023-05-07 08:45
me i can run it with gasstation

**Comment by quentin452** [comment] 2023-05-07 08:45
its not a crash caused by gasstation , its caused by an incompat between multithreading and tweaks and falsetweaks

**Comment by iamsoNewBee** [comment] 2023-05-07 08:48
strange

**Comment by quentin452** [comment] 2023-05-07 08:48
for now you can disabling voxelizer from falsetweaks

**Comment by iamsoNewBee** [comment] 2023-05-07 08:54
one suipid question:so i can run  Multithreadingandtweaks without UniMixins .right?and i didnt crash with these mods but i meet crash when i use unimixins.

**Comment by quentin452** [comment] 2023-05-07 08:55
> one suipid question:so i can run Multithreadingandtweaks without UniMixins .right?and i didnt crash with these mods but i meet crash when i use unimixins.

You don't know ? that unimixin is like gasstation , its a mixin loader you can't run theses two mods at once

**Comment by iamsoNewBee** [comment] 2023-05-07 08:56
when i use unimixin i deleted gasstation

**Comment by iamsoNewBee** [comment] 2023-05-07 08:57
i also opened issue about that mod

**Comment by quentin452** [comment] 2023-05-07 08:57
whats the crash report?

**Comment by iamsoNewBee** [comment] 2023-05-07 08:59
https://github.com/LegacyModdingMC/UniMixins/issues/11

**Comment by quentin452** [comment] 2023-05-07 09:04
so i maked some tests and it seem that cannot be fixed in multithreading side , lets try to change the source code from falsetweaks

**Comment by quentin452** [comment] 2023-05-07 09:53
Fox now I don't know whats the problem , i just know what class cause the problem , but idk why

**Comment by quentin452** [comment] 2023-05-07 09:54
i will make an issue on falsetweaks side

**Comment by iamsoNewBee** [comment] 2023-05-07 09:57
u crash when u add multi adn falsetweaks?

**Comment by quentin452** [comment] 2023-05-07 09:59
its caused by TRIANGULATOR , but idk how to fix

**Comment by iamsoNewBee** [comment] 2023-05-07 10:01
i dont know why i dont crash.confusing and i dont konw where is your problem(??)

**Comment by quentin452** [comment] 2023-05-07 10:14
for the clarity , the game crash if you have multithreading and tweaks and falsetweaks enabled with triangulator enabled from falsetweaks

**Comment by quentin452** [comment] 2023-05-07 16:40
fixed by updating falsepatternlib

**Closed by quentin452** 2023-05-07 16:40 UTC
Labels: bug, priority high
