### ISSUE TITLE
[1.7.10]: Crash with Alfheim

### ISSUE THREAD

**Issue by Rimusp** [quentin452/Multithreadingandtweaks#98] opened 2024-01-16 18:43 UTC
### Help isloating the issue

- [ ] Did you tried to disabling some mixins in the mod config to see what mixin made the issue?
- [ ] Did you find what mixin made the issue?

### Game log

[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13954547/fml-client-latest.log)

### Description

Crashes on load with Alfheim mod no idea where to even start with mixins

**Comment by quentin452** [comment] 2024-01-16 18:46
fixed in dev now , to fix the crash just put to false 'enableMixinBiomeGenBase" in Optimizationsandtweaks

**Comment by Rimusp** [comment] 2024-01-16 18:57
that worked but now it crashes when trying to create or load a world
[fml-client-latest.log](https://github.com/quentin452/OptimizationsAndTweaks/files/13954674/fml-client-latest.log)

**Comment by quentin452** [comment] 2024-01-16 19:03
its probably a bug caused by Alfheim itself

**Comment by Rimusp** [comment] 2024-01-16 19:05
ok will report to them thanks anyways

**Comment by Rimusp** [comment] 2024-01-16 22:13
testet some mixins and found that "enableMixinEntityRenderer" is causing the crash

**Closed as completed** 2024-01-17 08:48 UTC
Labels: bug
